[tool.black]
exclude = '''
(
  /(
      \.git          # root of the project
    | \.mypy_cache
  )/
)
'''

[tool.mypy]
exclude = [
    "^build/$",
    # Can't type check as we don't install Superset:
    "^airtabledb/db_engine_specs.py$",
]

plugins = "sqlalchemy.ext.mypy.plugin"
